main: com.winthier.rph.RandomPlayerHeadPlugin
name: RandomPlayerHead

version: 0.1
api-version: 1.19

author: StarTux
website: https://cavetale.com
description: Spawn in random player heads

depend: [Core, Mytems]
softdepend: []

commands:

  randomplayerhead:
    aliases: [rph]
    description: Spawn in a random player head
    usage: |-
      /rph <player> [name] - Spawn in one (random) head.
      /rph -search <name> - Search heads database.
      /rph -all(m) <name> - Spawn in all matching heads.
      /rph -reload - Reload config files.
    permission: rph.rph

  makeplayerhead:
    aliases: [mph]
    description: Make a head from its give code
    usage: |-
      /mph <name> <id> <texture> - Spawn the head
    permission: rph.mph

  head:
    aliases: []
    description: Get the head of an actual player
    usage: |-
      /head <name> - Spawn the head
    permission: rph.head

  headstore:
    aliases: []
    description: Open the head store
    usage: /headstore - Open the head store
    permission: rph.store

permissions:

  rph.rph:
    description: Use /rph
    default: op

  rph.mph:
    description: Use /mph
    default: op

  rph.head:
    description: Use /head
    default: op

  rph.store:
    description: Use /headstore
    default: op

  rph.store.open:
    description: Open the store without command
    default: op