name: RandomPlayerHead
description: Spawn in random player heads
author: StarTux
version: 0.1
api-version: 1.13
website: https://cavetale.com
main: com.winthier.rph.RandomPlayerHeadPlugin
depend: []

commands:
  randomplayerhead:
    aliases: [rph]
    description: Spawn in a random player head
    usage: |-
      /rph <player> [name] - Spawn in one (random) head.
      /rph -search <name> - Search heads database.
      /rph -all(m) <name> - Spawn in all matching heads.
      /rph -reload - Reload config files.
    permission: rph.rph

  makeplayerhead:
    aliases: [mph]
    description: Make a head from its give code
    usage: |-
      /mph <name> <id> <texture> - Spawn in head
    permission: rph.mph

permissions:
  rph.rph:
    description: Use /rph
    default: op
  rph.mph:
    description: Use /mph
    default: op